### ISSUE TITLE
Footer Content

### ISSUE THREAD

**Issue by josefigueroa168** [TheRensselaerIDEA/COVID-DI-Prototype#106]
* Should add relevant content and links to footer.
* Cleaner more modern styling
* Copyright/open source stuff

**Comment by josefigueroa168** [comment]
* No need to have data source and analysis on the left column if it's in the footer
* Separate the data sources by commas and wrap them, instead of stacking them
* Consider smaller font for footer
* Don't smoosh the "Statement of accessibility" in with the other links. It needs to be prominent;t he Institute policy people are looking for it. So it needs to be at the bottom and clear and separate. Like over on the left, separated by a <br> or whatever

-John suggestions

**Comment by olyerickson** [comment]
I basically did all of these; CLOSING. I've got more footer suggestions however!
