### ISSUE TITLE
Make the disparity index correct  and working well

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVID-DI-Prototype#19]
-mathematics correct
-figure out how to make it good or bad consistently

**Comment by olyerickson** [comment]
TODO: Merge this ticket with the "colors" ticket. 

NOTE: Current implementation matches AMIA abstract colors and scale (all plots)

**Comment by olyerickson** [comment]
CLOSING this because covered by other (closed) ticket(s)
