### ISSUE TITLE
Make disparity index color scheme identical for all factors. 

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVID-DI-Prototype#22]

**Comment by olyerickson** [comment]
Does this mean normalize the range? As well as making the palette match Miao's

**Comment by bennek2** [comment]
Use the same colors for same ranges on all plots.  There is no normalization besides the one that the metric already makes intrinsically.  for example -0.2 to 0.2 means no significant disparities on all plots and has the same color.

**Comment by olyerickson** [comment]
DONE in the four (so far...) prototype maps. 

- Disparity Index, Hospital Beds: http://orion.tw.rpi.edu/~olyerickson/ldi_hosp_beds.html
- Disparity Index, Total COVID-19 Tests: http://orion.tw.rpi.edu/~olyerickson/ldi_tests.html
- Disparity Index, Total At-Risk Adults 18 & Older: http://orion.tw.rpi.edu/~olyerickson/ldi_at_risk_adults.html
- Disparity Index, Share of Older At-Risk Adults: 
http://orion.tw.rpi.edu/~olyerickson/ldi_older_at_risk_adults.html

**Comment by olyerickson** [comment]
I'm going to close this issue, based on the current prototypes; we can open a new issue if we e.g. need to align colors with bad- or good-ness.
