### ISSUE TITLE
Do one Testing map really well 

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVID-DI-Prototype#30]
How about if we go deep on one visualization and make it pretty?  Let's do amount testing  and compare to  South Korea rate.   We need a better US map (with alaska and hawaii down below)  Nice headers. Red should mean bad (underrepresented testing).  We may want to introduce more fined grained colors. Then I can circulate and get feedback from advisors.  Needs a nice label on top.  We need some text saying where we are at.    Also do the same map showing just straight rates for comparison to illustrate the value of disparity rates.  Ideallymake it toggle between the two

**Comment by bennek2** [comment]
Background rate is  6,768 tests per million for South Korea

**Comment by olyerickson** [comment]
I *think* we satisfied this request; closing this issue.
