### ISSUE TITLE
Deaths plot has inaccurate DI

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVID-DI-Prototype#51]
Shows NY as negative but it should be very positive.

**Comment by kb22** [comment]
I believe this has been fixed as NY now has value between 2.0 and 5.0

<img width="355" alt="Screen Shot 2020-04-03 at 12 47 10 PM" src="https://user-images.githubusercontent.com/14316277/78385088-4c679100-75a9-11ea-8216-e5c1a1a65357.png">
